Repository alma/widgets, pull requests merged in 2025-02, with the labels that each got.

#162 Update readme and example files to use v4
  .github/workflows/purge-js-delivr-cache.yml
  README.md
  examples/basic.html
  examples/multiple.html
Labels: type: docs

#163 Fix config to display build number in user agent
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: type: feature

#167 Remove map files from list to purge jsdelivr cache & fix quote typo
  .github/workflows/purge-js-delivr-cache.yml
Labels: type: bugfix

#168 Fix/cache for eligibility
  src/hooks/useFetchEligibility.ts
  src/hooks/useSessionStorage.tsx
  src/types.ts
  src/utils/fetch.ts
Labels: type: bugfix

#169 chore(test): add basic tests for useFetchEligibility hook
  src/hooks/useFetchEligibility.test.ts
Labels: type: chore
